### ISSUE TITLE
決済処理中ロールバックによって会員ログイン中の画面でエラーが出る不具合

### ISSUE THREAD

**Issue by izayoi256** [EC-CUBE/eccube-2_13#1]
SC_Helper_Purchase::rollbackOrder($order_id, $orderStatus = ORDER_CANCEL, $is_delete = false)で決済処理中の受注をロールバックする場合、
1. 決済処理中の受注を取得し、その受注IDでステータスをキャンセルに変更する。
2. その受注IDに紐づく一時受注を取得する。
3. 一時受注の削除フラグを0にして保存する。
という手順を踏みます。
しかし、受注ステータスが決済処理中で、かつ一時受注が存在しない受注が存在する場合、
2で一時受注が取得できず、そのまま3で保存しようとするためDBエラーが発生します。
このロールバック処理はPENDING_ORDER_CANCEL_FLAGがtrueで会員ログイン時はページ読み込み毎に呼び出されるため、上記の条件に合致する受注を持つ会員は毎回エラーページが表示されます。
そのため3の手順を
3. 「一時受注が存在する場合、」一時受注の削除フラグを0にして保存する。
に変更する必要があります。

再現方法:
PENDING_ORDER_CANCEL_FLAGをtrueに変更する。
受注登録画面で任意の会員+決済処理中のステータスで受注を登録する。
受注登録した会員でログインする。

**Comment by Yangsin** [comment]
ありがとうございます。
こちらクローズさせていただきます。
