### ISSUE TITLE
郵便番号CSVが存在しないとエラー停止する不具合を修正

### ISSUE THREAD

**Issue by seasoftjapan** [EC-CUBE/eccube-2_13#10]

**Comment by Yangsin** [comment]
郵便番号CSV登録の不具合修正と合わせたPRとなっておりましたが、このままとりこみました。

・SVN で dummy が存在しなかった空ディレクトリーが無かった事になっている問題を一部のみ修正
・へんてこなswitchを修正した

PR、コミットは小さくしていただき、コメントもタイトルと仔細をわけるような形にしていただけると、理解がしやすく助かります。

参考：　http://qiita.com/itosho/items/9565c6ad2ffc24c09364

**Comment by Yangsin** [comment]
ひとまず、こちらはクローズとさせていただきます。
PRありがとうございます。
