### ISSUE TITLE
SC_FormParam::checkErrorのswitch文のdefaultでエラーメッセージを入れないようにしてほしい

### ISSUE THREAD

**Issue by kurozumi** [EC-CUBE/eccube-2_13#112]
SC_FormParam::checkErrorのswitch文のdefaultでエラーメッセージを入れないようにしてほしいです。
これがあるのでプラグインを開発するときにSC_FormParam::checkErrorが拡張出来なくて困っています。

以下のように拡張したいのですが、
https://gist.github.com/kurozumi/93f1f85bfd60aee0629183af4f222e35
KANANUM_CHECKに引っかからなかった時、「エラーチェック形式($func)には対応していません」というメッセージが表示されてしまいます。

**Comment by seasoftjapan** [comment]
拡張処理を先に実行して、`'KANANUM_CHECK'` を unset() して、parent::checkError() を呼び出すとかで対応できませんか?

**Comment by kurozumi** [comment]
アドバイス通り、以下のように修正したら問題が解決しました。

https://gist.github.com/kurozumi/9c5af56d63e728f868a752399c8c3b0e

ありがとうございました！
