### ISSUE TITLE
SC_Helper_Customer::sfGetCustomerData() del_flg をチェックしていない

### ISSUE THREAD

**Issue by seasoftjapan** [EC-CUBE/eccube-2_13#118]
削除済み・退会済みの情報を読み込めそう。
管理画面でハック的手法などで、本来表示されるべきでない会員情報を表示できたり、(登録まで至れると) del_flg = 0 に戻ってしまったり、意図しない動作を招きそうに思う。
sfGetCustomerDataFromId() も同様か。

**Comment by so-amuamu** [comment]
直接的な動作への影響は無さそうですが
SC_Helper_Customer内のdel_flg条件は足して揃える方向で直しましょう
