### ISSUE TITLE
SC_CartSession::delProductKey() 末尾の要素を扱えない

### ISSUE THREAD

**Issue by seasoftjapan** [EC-CUBE/eccube-2_13#120]
こういうこと。for なんて使うから…
```diff
-for ($i = 0; $i < $max; $i++) {
+for ($i = 0; $i <= $max; $i++) {
```

**Comment by izayoi256** [comment]
@seasoftjapan 
確かにforeachを使っていないことに疑問は覚えますが、標準で末尾の要素が扱えないケースがありますか？
カートの配列のキーに0未満の数字や数字以外の文字列を使っているのでなければ、動作はすると思うのですが。

**Comment by izayoi256** [comment]
@seasoftjapan あ、いや発生しますね。私の勘違いでした。

**Comment by nobuhiko** [comment]
#108
