### ISSUE TITLE
PHP7.1だとオーナーズストアと通信できない

### ISSUE THREAD

**Issue by mami-sugi** [EC-CUBE/eccube-2_13#130]
## 概要(Overview)
管理画面でモジュール一覧を取得しようとした際に、
エラーが発生してオーナーズストアと通信できない。

## 期待する内容(Expect)  or 要望 (Requirement)
オーナーズストアと通信して、購入したモジュールを取得できる。

## 再現手順(Procedure)
管理画面でオーナーズストア＞モジュール管理でモジュール一覧を取得するを押した際、
エラーが発生し、処理が終わらない。

```
PHP Parse error:
 syntax error, unexpected new (T_NEW) in /var/www/html/eccube217/data/module/HTTP/Request.php on line 412,
referer: http://xxx.xxx.xxx.xxx/eccube217/html/admin/ownersstore/module.php
```
### 環境 (environment)

ブランチ：improve/php7

+ EC-CUBE: 2.17
  - PHP: 7.1.8
  - DB: PostgreSQL 9.2.18

## 関連情報 (Ref)
無し

**Comment by nobuhiko** [comment]
#166 にて修正済み
