### ISSUE TITLE
郵便番号DB登録　自動登録と郵便番号CSV更新が実行できない

### ISSUE THREAD

**Issue by arisgi** [EC-CUBE/eccube-2_13#133]
## 概要(Overview)
管理画面の「基本情報管理＞郵便番号DB登録」にて
自動登録 または 郵便番号CSV更新 を実行しようとするとシステムエラーが発生する。

## 期待する内容(Expect)  or 要望 (Requirement)
正常に実行させたい。

## 再現手順(Procedure)
管理画面の「基本情報管理＞郵便番号DB登録」にて
自動登録 または 郵便番号CSV更新 を押下する。

▼PHP7環境
```
PHP Parse error:  syntax error, unexpected new (T_NEW) in /var/www/html/eccube217/data/module/HTTP/Request.php on line 801, 
referer: http://xxx.xxx.xxx.xxx/eccube217/html/admin/basis/zip_install.php?
```

▼PHP5環境
```
PHP Fatal error:  Cannot redeclare class Net_URL in /var/www/html/eccube217/data/module/Net/URL.php on line 41, 
referer: http://xxx.xxx.xxx.xxx/eccube217/html/admin/basis/zip_install.php
```

### 環境 (environment)

ブランチ：improve/php7

+ PHP7環境
  - PHP: 7.1.8
  - DB: PostgreSQL 9.2.18
+ PHP5環境
  - PHP: 5.4.16
  - DB: MySQL 5.5.57

## 関連情報 (Ref)
なし

**Comment by nanasess** [comment]
こちらなどに置き換えしてしまっても良いのではないでしょうか？
https://github.com/yubinbango/yubinbango

**Comment by seasoftjapan** [comment]
修正しようかと思いましたが、コアな部分でもないので外部の ASP 利用でも良いと思います。

プラグインとして同梱しておけば、別の ASP への切り替えなんかもスムースかなと思ったりもしますが、競合を生じやすくなったりする支障が懸念されると嫌ですね。

**Comment by nobuhiko** [comment]
#166 にて修正済み
