### ISSUE TITLE
PostgreSQLだと規格名が正常に表示されない

### ISSUE THREAD

**Issue by arisgi** [EC-CUBE/eccube-2_13#137]
## 概要(Overview)
商品一覧・商品詳細ページにおいて、
規格名を表示する箇所で不具合が生じる。

![image](https://user-images.githubusercontent.com/16891862/29903316-3cfb1246-8e3e-11e7-8bc9-397dbba55144.png)

## 期待する内容(Expect)  or 要望 (Requirement)
正常に表示したい。

## 再現手順(Procedure)
+ 商品一覧ページにおいて,規格がある商品のフォームで規格名のラベルが表示されていない
+ 商品一覧ページにおいて,規格がある商品のフォームのエラーメッセージで規格名が文字化け
+ 商品詳細ページにおいて,規格がある商品のフォームで規格名のラベルが表示されていない
+ 商品詳細ページにおいて,規格がある商品のフォームのエラーメッセージで規格名が文字化け

### 環境 (environment)

ブランチ：improve/php7

+ PHP: 7.1.8
+ DB: PostgreSQL 9.2.18

**Comment by nanasess** [comment]
この修正で直りますでしょうか？
https://github.com/nanasess/ec-cube-extended/pull/48/files

**Comment by nanasess** [comment]
対応済みですので close します
