### ISSUE TITLE
7.1での文字列の演算でのE_WARNINGの対処法

### ISSUE THREAD

**Issue by ryo-endo** [EC-CUBE/eccube-2_13#140]
From @kiyosue on 15 May, 2017
Copied from original issue: nanasess/ec-cube-extended/issues/29

---

7.1から、文字列と数値を算術演算すると、E_WARNINGが発生するように
なりました。
無効な文字列による算術演算の通知
https://secure.php.net/manual/ja/migration71.other-changes.php
具体的なエラーは
2017/05/15 19:11:08 [/index.php] Warning(E_WARNING): A non-numeric value encountered on [/vagrant/data/class/helper/SC_Helper_TaxRule.php(106)]
とかになります。

これの対処法を検討したいです。
エラーが発生する箇所は、主に、空文字列をゼロとキャストしてくれる事を期待したコードになってます。

空文字列と演算している所を片っ端からキャストするととりあえずは対応できますが、それ以上するのであれば、

関数の引数で型の宣言をきちんといれる。という事もできます。
それで解決はしませんが、型以外の引数がくると、Fatal errorが発生するようになります。

他に、一端無視ともできますが、相談で起票しておきます。

**Comment by nanasess** [comment]
とり急ぎ cast で対応済みですので close します
