### ISSUE TITLE
data/module 以下の Composer への置き換え

### ISSUE THREAD

**Issue by ryo-endo** [EC-CUBE/eccube-2_13#143]
From @nanasess on 17 May, 2017
Copied from original issue: nanasess/ec-cube-extended/issues/37

---

関連 nanasess/ec-cube-extended/issues/8
置き換え可能なものは、 Composer で管理する

**Comment by okazy** [comment]
間違ってクローズしてしまいましたのでリオープンします。

**Comment by nanasess** [comment]
対応済みですので close します。
