### ISSUE TITLE
HTTP_REQUEST使用部分でエラーになる。

### ISSUE THREAD

**Issue by ryo-endo** [EC-CUBE/eccube-2_13#145]
From @yuh4 on 22 Aug, 2017
Copied from original issue: nanasess/ec-cube-extended/issues/42

---

郵便番号の自動登録部分でエラー。
PEARのHTTP_REQUESTが原因
ほかの使用部分はLC_Page_Upgrade_Base.php

**Comment by nanasess** [comment]
以下で対応済み
https://github.com/EC-CUBE/eccube-2_13/commit/384ac2ce07d2aac9f8134b133cbb48b50d22154c
