### ISSUE TITLE
Smartyプラグインのエラー

### ISSUE THREAD

**Issue by ryo-endo** [EC-CUBE/eccube-2_13#146]
From @yuh4 on 24 Aug, 2017
Copied from original issue: nanasess/ec-cube-extended/issues/43

---

Smartyのプラグイン内で

```
require_once $smarty->_get_plugin_filepath('shared', 'escape_special_chars');
```

このように記載されている箇所で、_get_plugin_filepathのメソッドが無い事が原因でエラーが発生します。
該当箇所は管理画面＞商品並び替えで商品表示時。

```
require_once DATA_REALDIR.'smarty_extends/shared.escape_special_chars.php';
```

このように変更で解決しますが、スマートじゃないのでどうしましょう。。

**Comment by nanasess** [comment]
こちらで修正済みですね
https://github.com/EC-CUBE/eccube-2_13/commit/68b68153025784620dcb6f1c73b5a831040912c2

**Comment by ryo-endo** [comment]
ありがとうございます。CLOSEします。
