### ISSUE TITLE
vendorのインストール先をdata/vendorにする

### ISSUE THREAD

**Issue by ryo-endo** [EC-CUBE/eccube-2_13#147]
直下にvendorを作成するのは、動作環境によっては配置できないケースがあるため。
詳細は、https://github.com/EC-CUBE/eccube-2_13/pull/128#issuecomment-319578444

対応方法は以下のコメントを参照
https://github.com/EC-CUBE/eccube-2_13/pull/128#issuecomment-320161015

**Comment by seasoftjapan** [comment]
プルリクしてみた https://github.com/EC-CUBE/eccube-2_13/pull/152

**Comment by nanasess** [comment]
対応済なので close します
