### ISSUE TITLE
PHP7対応のエラーチェック

### ISSUE THREAD

**Issue by yuh4** [EC-CUBE/eccube-2_13#156]
[eccube　PHP7対応不具合リスト.xlsx](https://github.com/EC-CUBE/eccube-2_13/files/1283441/eccube.PHP7.xlsx)
会社でEC-CUBE2系のPHP7対応でエラーチェックを行ったリストです。
すでに修正された箇所もあるかと思いますが、共有します。

**Comment by so-amuamu** [comment]
御手数ですが、既存との重複や解決済み確認をして残るものをissueへの分解･登録
だれかお願い出来ませんか

**Comment by nanasess** [comment]
@so-amuamu こちらで確認しますね

**Comment by nobuhiko** [comment]
4の・HTMLメールのプレビューで改行が効いていない。は<br>をいれれば改行されたのでそういう仕様でしょうかね？

**Comment by nobuhiko** [comment]
@so-amuamu 
EC-CUBEデフォルトのバグ というシート以外は全部チェックして、再現するものはプルリクしました

**Comment by nanasess** [comment]
対応できていなくてすみません。ありがとうございますm(_ _)m

**Comment by so-amuamu** [comment]
@nobuhiko 
ありがとうございます！GJ!
レビューします
