### ISSUE TITLE
基本情報管理＞税率設定 編集時にセレクトボックスの値が未選択となる

### ISSUE THREAD

**Issue by seasoftjapan** [EC-CUBE/eccube-2_13#159]
「基本情報管理＞税率設定」画面で、「共通税率設定」で編集すると、「適用日時」の「月」「日」「時」「分」が未入力となるケースがある。

値が1桁の場合に発生する模様。おそらく、Smarty の html_options の selected 属性の比較が、「==」から「===」に仕様変更されている。

#136 も同じ原因か。

ブランチ：improve/php7

**Comment by yuh4** [comment]
explodeで日付を分解してるので、intに変換する事で正常に動作するようになるみたいです。

**Comment by nobuhiko** [comment]
直っているのでクローズ
