### ISSUE TITLE
mb_convert_kana パラメーターが局所的に冗長

### ISSUE THREAD

**Issue by seasoftjapan** [EC-CUBE/eccube-2_13#16]

**Comment by Yangsin** [comment]
pull #17 を取り込みましたが、他にもあるかもしれませんので、Issueは残しておきます。

**Comment by nobuhiko** [comment]
grepした限りではないようです（KVna）のパターンは

**Comment by seasoftjapan** [comment]
/[KVna]{4}/ も大丈夫だったと思います。
けど、n a 重複は他のパターンでもありえるので、もう少し検証できると良いですね。

**Comment by Yangsin** [comment]
こちらクローズいたします。
