### ISSUE TITLE
jQueryのバージョンアップによる不具合

### ISSUE THREAD

**Issue by nobuhiko** [EC-CUBE/eccube-2_13#18]
- 商品の規格登録・編集で在庫無制限を解除しても在庫が登録できない

**Comment by Yangsin** [comment]
ありがとうございます。pull #19 とりこみましたので、クローズします。

**Comment by Yangsin** [comment]
propに直したほうがいいのじゃないかという議論があるのでReopenします。

**Comment by nobuhiko** [comment]
他にもたくさんありそうなので、チケットのタイトルも変えます
http://xoops.ec-cube.net/modules/newbb/viewtopic.php?topic_id=15537&forum=10&post_id=69449#forumpost69449

**Comment by Yangsin** [comment]
2.13.4の対応としてはクローズさせていただきます。
