### ISSUE TITLE
モバイル(ガラケー)サイトの廃止

### ISSUE THREAD

**Issue by nanasess** [EC-CUBE/eccube-2_13#194]
- もうガラケーで https にアクセスできない時代になってしまったので、この際削除してしまってよいと思われる
- Net_UserAgent_Mobile/Net/UserAgent/Mobile/DoCoMo/ScreenInfo.php の 2088行目に、無効な参照代入があるため、ガラケーを活かすのであれば、 composer を使わずローカルに持ってくる必要がある
- 最低限の下位互換性のため、 既存のクラスや定数は残しておく
   - `SC_MobileUserAgent` のメソッドは常に false  or null を返す

**Comment by nanasess** [comment]
see also
- https://github.com/EC-CUBE/eccube-2_13/pull/193
- https://github.com/EC-CUBE/eccube-2_13/issues/132

**Comment by so-amuamu** [comment]
動作無効にして、コード類は置いておく。
表向きはNot supportにしましょう

**Comment by so-amuamu** [comment]
管理画面系も隠さないと駄目ですかね？

**Comment by nanasess** [comment]
管理画面はそのままでいいような

**Comment by nobuhiko** [comment]
ナビだけコメントアウトするぐらいならすぐ出来ますが

**Comment by Yangsin** [comment]
いまのところ不要という意見しかないようですので、
メンテナー6名の過半数の同意 ｏｒ 8月6日（月）までに反対意見がないなら
 @so-amuamu のご提案いただいた以下ので内容でDisscussion終えましょう。

```
動作無効にして、コード類は置いておく。
表向きはNot supportにしましょう
```

**Comment by so-amuamu** [comment]
ショップ運営者が迷う要素になるので、ナビのコメントアウトだけはしましょうかね
> ナビだけコメントアウトするぐらいならすぐ出来ますが

**Comment by Yangsin** [comment]
誤って本日マージされてますが、反対意見などがあれば戻すということで。
