### ISSUE TITLE
Windows 版 PHP7 の環境で CSV アップロードに失敗する？

### ISSUE THREAD

**Issue by nobuhiko** [EC-CUBE/eccube-2_13#222]
2系も関係する可能性あり？
https://github.com/EC-CUBE/ec-cube/pull/1781

**Comment by nobuhiko** [comment]
#156 の2件が可能性あります。
- カテゴリーのCSV登録ができない。
- ダウンロードした商品を変更せずにそのままCSV登録を行うとエラーが発生する。

**Comment by nanasess** [comment]
これは該当しそうですね。
https://github.com/EC-CUBE/eccube-2_13/blob/9785237d7f211380142191fd599829d4b57acebc/data/class/SC_Initial.php#L143-L149
おそらく、日本語版 Windows の場合、ここで CP932(SJIS-win) のロケールが設定されるので、 PHP7以降では CP932 のファイルエンコーディングを使用する必要があると思います。
