### ISSUE TITLE
管理画面へのアクセス制御

### ISSUE THREAD

**Issue by Yangsin** [EC-CUBE/eccube-2_13#234]
管理画面へのアクセス制御を強化する

+ 管理画面は  noindex    とする → 対応済み
+ .htaccess でベーシック認証のサンプルを用意（デフォルトコメントアウト）
+ 初期インストール時に admin  でのインストールはエラーとする
+ url が /admin となっている場合に警告 

くらいを入れておきたい。

**Comment by nobuhiko** [comment]
- 管理画面は noindex とする

これはもうなっています

**Comment by so-amuamu** [comment]
3系、４系と歩調を合わせ、本件を対応した上で、リリースに向けた最終作業に進めたいと思います
