### ISSUE TITLE
不要なライブラリの削除

### ISSUE THREAD

**Issue by chihiro-adachi** [EC-CUBE/eccube-2_13#242]
使用していないが、本体に依存コードがあり削除できないライブラリを削除する
以下が対象となる
- Services_JSON 
- Net_UserAgent_Mobile
- Cache_Lite

#241

**Comment by nanasess** [comment]
Cache_Lite も消したいです。SC_Cache というクラスはありますが、使用されてません

**Comment by chihiro-adachi** [comment]
更新しました
他にもあれば随時コメントいただければー

**Comment by nanasess** [comment]
pear/SOAP あたりを消せると pear/xml_* 関連をごそっと消せるはずですが、、決済で使ってるっぽいので厳しいか🤔

**Comment by chihiro-adachi** [comment]
#243 で対応

@nanasess こちらのissueはクローズで問題ないでしょうか？

**Comment by nanasess** [comment]
@chihiro-adachi 問題ないです

**Comment by chihiro-adachi** [comment]
@nanasess ありがとうございます！
