### ISSUE TITLE
SC_Helper_PurchaseのgetDelivDate中のコメントが実際の内容と微妙に合っていない

### ISSUE THREAD

**Issue by shutta-** [EC-CUBE/eccube-2_13#245]
SC_Helper_PurchaseのgetDelivDate中のコメントが、mtb_delivery_dateの内容と微妙に合っていない。
完全に一致させる必要はないと思うが、「○週間以内」の部分が、「以内」と「以降」では意味が違ってくるので、この部分だけは修正しておいた方が良いかなと。

**Comment by chihiro-adachi** [comment]
#245 で対応。

**Comment by shutta-** [comment]
> #245 で対応。

#246 で対応ですね。
