### ISSUE TITLE
管理機能＞商品選択ポップアップ画面で規格2のonchangeに存在しないfnCheckStock()が使われている

### ISSUE THREAD

**Issue by clicktx** [EC-CUBE/eccube-2_13#25]
http://svn.ec-cube.net/open_trac/changeset/23448 で削除されていると思われるfnCheckStock()が templates/admin/order/product_select.tpl で呼び出されている。

```
<dd>
    <select name="classcategory_id2" id="<!--{$class2}-->" style="<!--{$arrErr[$class2]|sfGetErrorColor}-->" onchange="fnCheckStock(this.form);"></select>
    <!--{if $arrErr[$class2] != ""}-->
    <br /><span class="attention">※ <!--{$tpl_class_name2[$id]}-->を入力して下さい。</span>
    <!--{/if}-->
</dd>
```

**Comment by clicktx** [comment]
そもそもeccube.jsでchangeイベントとして書かれているので、規格1にある `onchange="fnSetClassCategories(this.form);"`も不要っぽい。

ただし、product_select.tpl 内にある function fnSetClassCategories()自体は必要。ページ描写時に規格2を設定している。

**Comment by so-amuamu** [comment]
本件、残っているので直す
