### ISSUE TITLE
会員登録時の確認用Eメールアドレス入力がコピペ許可になっているため、効果がない。

### ISSUE THREAD

**Issue by scubism-tech-share** [EC-CUBE/eccube-2_13#27]
## 概要
　会員登録時の確認用Eメールアドレス入力がコピペ許可になっているため、確認用途で設置するには効果が薄い。
　結果的に、Eメールアドレスの誤入力を誘発する可能性が上がる。

## 対応
　スマホ、PCの会員登録入力フォームにおいて、該当カラムのコピペ入力を付加とする。

**Comment by shinichi-takahashi** [comment]
コメントありがとうございます。
紐付くPRをMergeさせていただいたので、本件クローズいたします。
