### ISSUE TITLE
"お届け先を指定"チェックボックスにチェックがないと"お届け先を複数指定する"ボタンが表示されない(SP)

### ISSUE THREAD

**Issue by scubism-tech-share** [EC-CUBE/eccube-2_13#29]
## 概要
画面：スマートフォン,"会員登録をせずに購入"時のお客様情報入力画面
現象："お届け先を指定"チェックボックスにチェックがないと"お届け先を複数指定する"ボタンが表示されない。
  
  配送先を複数指定する際に"お届け先を指定"チェックボックスをチェックする必要がある。
  結果、お客様情報入力画面にて別の配送先情報を入力しなければ次の画面に進むことができない。
## 対応
　ボタンの表示位置を変更、PC同様にお届け先の複数指定ができるよう修正。

**Comment by Yangsin** [comment]
wontfix でCloseせていただきます。
