### ISSUE TITLE
送料を0にできる不具合

### ISSUE THREAD

**Issue by ArtemisHaD** [EC-CUBE/eccube-2_13#54]
やり方
送付先の都道府県を設定するときにページのソースをいじり，
北海道=1, 青森=2,...と割り当ててある都道府県のIDを0に設定し送信する．

こうすることで処理が適切に行われず送料が0円に設定されるようです．

**Comment by migarashi47** [comment]
```
$objFormParam->addParam('都道府県', $prefix . 'pref', INT_LEN, 'n', array('EXIST_CHECK', 'NUM_CHECK', 'PREF_CHECK'));
```

のような感じで`PREF_CHECK`メソッドを新規に追加してmtb_prefの最大最小値の範囲に収まっているかどうかを検査しようと思いますが、どうでしょうか

**Comment by nanasess** [comment]
最大最小値のチェックよりも、マスタの存在チェックの方が良さそうですが、いかがでしょう。
海外向けに 「99: その他」などを追加カスタマイズする場合もありますので。

**Comment by migarashi47** [comment]
@nanasess 
マスタチェックで直しました、どうでしょうか

**Comment by nanasess** [comment]
@migarashi47 ありがとうございます！後ほど検証して、問題なければ採用したいと思います。

**Comment by ryo-endo** [comment]
修正の取り込み完了しました。
