### ISSUE TITLE
新着情報管理　順番の変更が出来ない

### ISSUE THREAD

**Issue by yuki-ishihara** [EC-CUBE/eccube-2_13#63]
### 概要

「□番目に移動」の□内に全角数字を入力すると移動が出来ない。エラー文も表示されない。「商品の並び替え」は全角数字でも移動する。
### 発生個所

管理画面>コンテンツ管理＞新着情報管理
### 頻度

常に起こっていると思われる。

Masterをチェックアウトして確認しています。

**Comment by migarashi47** [comment]
直しました。全角数字は受け付けてません

**Comment by ryo-endo** [comment]
修正取り込みましたのでCLOSEします。
