### ISSUE TITLE
追加した届け先の内容を修正しようとした時、内容をそのままに実行するとエラーが出る

### ISSUE THREAD

**Issue by nobuhiko** [EC-CUBE/eccube-2_13#7]
開発フォーラムにて報告がありました
デフォルトの2.13.3で再現します

http://xoops.ec-cube.net/modules/newbb/viewtopic.php?topic_id=15484&post_id=69233&order=0&viewmode=flat&pid=69230&forum=8#forumpost69233

**Comment by Yangsin** [comment]
マージ済みですので、クローズします。ありがとうございます。
