### ISSUE TITLE
cvs出力で特定ユーザが出力されない

### ISSUE THREAD

**Issue by nobuhiko** [EC-CUBE/eccube-2_13#73]
フォーラムより
http://xoops.ec-cube.net/modules/newbb/viewtopic.php?topic_id=16652&forum=11&post_id=73501#forumpost73501

データ移行csvとかでも抜けて痛い目にあいます

**Comment by so-amuamu** [comment]
フォーラムの力技のvalidationでは不完全かと思われる。

そもそも、今のご時世でSJIS出力の事を考えるべきなのか対応すべきなのか判断も難しい。

実際問題としては送り状出力や決済などでSJISに使えない文字は利用禁止で、多くのサイトや決済モジュールでそれぞれチェックルーチンも入れているので、日本のＥＣサイト向けとしては、対応するべきか？

GMO-PGモジュールのルーチンは参考になるかも？
UTF8->SJIS->UTF8の可逆性チェックでも不十分？

**Comment by so-amuamu** [comment]
リファレンスありましたか、見落としました失礼しました！
#90 がマージされたらクローズということで。
