### ISSUE TITLE
MySQL 5.7.5 以降でエラー発生

### ISSUE THREAD

**Issue by seasoftjapan** [EC-CUBE/eccube-2_13#84]
storage_engine <= 5.7.4
default_storage_engine >= 5.5.3

http://xoops.ec-cube.net/modules/newbb/viewtopic.php?topic_id=16981&post_id=74582&forum=2
http://dev.mysql.com/doc/refman/5.7/en/server-system-variables.html#sysvar_default_storage_engine
http://dev.mysql.com/doc/refman/5.5/en/server-system-variables.html#sysvar_default_storage_engine

**Comment by Yangsin** [comment]
対応方法・実装方法について、ご意見募集。
フォーラムのように分岐させるか？

**Comment by ryo-endo** [comment]
取り込みましたのでCLOSEします。
